
package default_package;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-03T20:42:53.501+05:30
 * Generated source version: 2.6.3
 */

@WebFault(name = "StockTradeInValidFormatException", targetNamespace = "http://default_package/")
public class StockTradeInValidFormatException_Exception extends Exception {
    
    private default_package.StockTradeInValidFormatException stockTradeInValidFormatException;

    public StockTradeInValidFormatException_Exception() {
        super();
    }
    
    public StockTradeInValidFormatException_Exception(String message) {
        super(message);
    }
    
    public StockTradeInValidFormatException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public StockTradeInValidFormatException_Exception(String message, default_package.StockTradeInValidFormatException stockTradeInValidFormatException) {
        super(message);
        this.stockTradeInValidFormatException = stockTradeInValidFormatException;
    }

    public StockTradeInValidFormatException_Exception(String message, default_package.StockTradeInValidFormatException stockTradeInValidFormatException, Throwable cause) {
        super(message, cause);
        this.stockTradeInValidFormatException = stockTradeInValidFormatException;
    }

    public default_package.StockTradeInValidFormatException getFaultInfo() {
        return this.stockTradeInValidFormatException;
    }
}
