
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.bizruntime.productavailabilityservice;

import java.util.List;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.cxf.binding.soap.interceptor.RPCOutInterceptor;

import com.bizruntime.UserProductServer.Product;
import com.bizruntime.UserProductServer.ProductAvailabilityService;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-06T10:31:46.781+05:30
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "productavailabilityservice",
                      portName = "productavailabilityserviceSOAPPort",
                      targetNamespace = "http://productavailabilityservice.bizruntime.com/",
                      wsdlLocation = "file:/D:/JOB/UserProductServer/src/main/webapp/wsdl/productavailabilityservice.wsdl",
                      endpointInterface = "com.bizruntime.productavailabilityservice.Productavailabilityservice")
                      
public class ProductavailabilityserviceImpl implements Productavailabilityservice {

    private static final Logger LOG = Logger.getLogger(ProductavailabilityserviceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.bizruntime.productavailabilityservice.Productavailabilityservice#getAllProductForUserForCategory(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.util.List<com.bizruntime.productavailabilityservice.Product> getAllProductForUserForCategory(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getAllProductForUserForCategory");
        System.out.println(arg0);
        System.out.println(arg1);
        
        try {
            ProductAvailabilityService service = new ProductAvailabilityService();
            List<Product> list = service.getAllProductForUserForCategory("U1001", "Mobile");
        	
            java.util.List<com.bizruntime.productavailabilityservice.Product> _return = new java.util.ArrayList<com.bizruntime.productavailabilityservice.Product>();
            com.bizruntime.productavailabilityservice.Product _returnVal1 = new com.bizruntime.productavailabilityservice.Product();
//            _returnVal1.setProductId("ProductId-2091586666");
//            _returnVal1.setProductName("ProductName496877030");
//            _returnVal1.setProductCategory("ProductCategory-1942324253");
//            _returnVal1.setPrice(0.29940617589673457);
//            java.util.List<java.lang.String> _returnVal1AvailableCity = new java.util.ArrayList<java.lang.String>();
//            java.lang.String _returnVal1AvailableCityVal1 = "_returnVal1AvailableCityVal1611182415";
//            _returnVal1AvailableCity.add(_returnVal1AvailableCityVal1);
//            _returnVal1.getAvailableCity().addAll(_returnVal1AvailableCity);
//            _return.add(_returnVal1);
            
            for (Product product : list) {
                _returnVal1.setProductId(product.getProductId());
                _returnVal1.setProductName(product.getProductName());
                _returnVal1.setProductCategory(product.getProductCategory());
                _returnVal1.setPrice(product.getPrice());
                java.util.List<java.lang.String> _returnVal1AvailableCity = product.getAvailableCity();
//                java.lang.String _returnVal1AvailableCityVal1 = "_returnVal1AvailableCityVal-1354227162";
//                
//                for (int i = 0; i < _returnVal1AvailableCity.size(); i++) {
//                	_returnVal1AvailableCity.add(_returnVal1AvailableCity.get(i));
//				}
//                
                _returnVal1.getAvailableCity().addAll(_returnVal1AvailableCity);
                _return.add(_returnVal1);

			}
            
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.productavailabilityservice.Productavailabilityservice#getAllProductForUser(java.lang.String  arg0 )*
     */
    public java.util.List<com.bizruntime.productavailabilityservice.Product> getAllProductForUser(java.lang.String arg0) { 
        LOG.info("Executing operation getAllProductForUser");
        System.out.println(arg0);

        try {
            ProductAvailabilityService service = new ProductAvailabilityService();
            List<Product> list = service.getAllProductForUser("U1001");
            java.util.List<com.bizruntime.productavailabilityservice.Product> _return = new java.util.ArrayList<com.bizruntime.productavailabilityservice.Product>();
            com.bizruntime.productavailabilityservice.Product _returnVal1 = new com.bizruntime.productavailabilityservice.Product();
//            _returnVal1.setProductId("ProductId-1363772410");
//            _returnVal1.setProductName("ProductName214378313");
//            _returnVal1.setProductCategory("ProductCategory2083520574");
//            _returnVal1.setPrice(0.10647454946497281);
//            java.util.List<java.lang.String> _returnVal1AvailableCity = new java.util.ArrayList<java.lang.String>();
//            java.lang.String _returnVal1AvailableCityVal1 = "_returnVal1AvailableCityVal-1354227162";
//            _returnVal1AvailableCity.add(_returnVal1AvailableCityVal1);
//            _returnVal1.getAvailableCity().addAll(_returnVal1AvailableCity);
//            _return.add(_returnVal1);
            
            for (Product product : list) {
                _returnVal1.setProductId(product.getProductId());
                _returnVal1.setProductName(product.getProductName());
                _returnVal1.setProductCategory(product.getProductCategory());
                _returnVal1.setPrice(product.getPrice());
                java.util.List<java.lang.String> _returnVal1AvailableCity = product.getAvailableCity();
//                java.lang.String _returnVal1AvailableCityVal1 = "_returnVal1AvailableCityVal-1354227162";
//                
//                for (int i = 0; i < _returnVal1AvailableCity.size(); i++) {
//                	_returnVal1AvailableCity.add(_returnVal1AvailableCity.get(i));
//				}
//                
                _returnVal1.getAvailableCity().addAll(_returnVal1AvailableCity);
                _return.add(_returnVal1);

			}
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
