
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.bizruntime.productavailabilityservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-05T12:54:29.897+05:30
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "productavailabilityservice",
                      portName = "productavailabilityserviceSOAPPort",
                      targetNamespace = "http://productavailabilityservice.bizruntime.com/",
                      wsdlLocation = "file:/D:/JOB/ProjectUserProduct/src/main/webapps/wsdl/productavailabilityservice.wsdl",
                      endpointInterface = "com.bizruntime.productavailabilityservice.Productavailabilityservice")
                      
public class ProductavailabilityserviceImpl implements Productavailabilityservice {

    private static final Logger LOG = Logger.getLogger(ProductavailabilityserviceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.bizruntime.productavailabilityservice.Productavailabilityservice#getAllProductForUserForCategory(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.util.List<com.bizruntime.productavailabilityservice.Product> getAllProductForUserForCategory(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getAllProductForUserForCategory");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<com.bizruntime.productavailabilityservice.Product> _return = new java.util.ArrayList<com.bizruntime.productavailabilityservice.Product>();
            com.bizruntime.productavailabilityservice.Product _returnVal1 = new com.bizruntime.productavailabilityservice.Product();
            java.util.List<java.lang.String> _returnVal1AvailableCity = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1AvailableCityVal1 = "_returnVal1AvailableCityVal-1605069828";
            _returnVal1AvailableCity.add(_returnVal1AvailableCityVal1);
            _returnVal1.getAvailableCity().addAll(_returnVal1AvailableCity);
            _returnVal1.setPrice(Double.valueOf(0.5768377246015947));
            _returnVal1.setProductCategory("ProductCategory593057437");
            _returnVal1.setProductId("ProductId2062082281");
            _returnVal1.setProductName("ProductName-1468385985");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.productavailabilityservice.Productavailabilityservice#getAllProductForUser(java.lang.String  arg0 )*
     */
    public java.util.List<com.bizruntime.productavailabilityservice.Product> getAllProductForUser(java.lang.String arg0) { 
        LOG.info("Executing operation getAllProductForUser");
        System.out.println(arg0);
        try {
            java.util.List<com.bizruntime.productavailabilityservice.Product> _return = new java.util.ArrayList<com.bizruntime.productavailabilityservice.Product>();
            com.bizruntime.productavailabilityservice.Product _returnVal1 = new com.bizruntime.productavailabilityservice.Product();
            java.util.List<java.lang.String> _returnVal1AvailableCity = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1AvailableCityVal1 = "_returnVal1AvailableCityVal1968157124";
            _returnVal1AvailableCity.add(_returnVal1AvailableCityVal1);
            _returnVal1.getAvailableCity().addAll(_returnVal1AvailableCity);
            _returnVal1.setPrice(Double.valueOf(0.27639517622211407));
            _returnVal1.setProductCategory("ProductCategory-2019880547");
            _returnVal1.setProductId("ProductId-133988632");
            _returnVal1.setProductName("ProductName-57063821");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
