package com.bizruntime.stocktrade;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-03T18:37:38.018+05:30
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://stocktrade.bizruntime.com/", name = "CSVStockTradeReader")
@XmlSeeAlso({ObjectFactory.class})
public interface CSVStockTradeReader {

    @WebMethod
    @RequestWrapper(localName = "getDailyTradingDifferential", targetNamespace = "http://stocktrade.bizruntime.com/", className = "com.bizruntime.stocktrade.GetDailyTradingDifferential")
    @ResponseWrapper(localName = "getDailyTradingDifferentialResponse", targetNamespace = "http://stocktrade.bizruntime.com/", className = "com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse")
    @WebResult(name = "_return", targetNamespace = "")
    public com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return getDailyTradingDifferential(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMaxVolumeTrade", targetNamespace = "http://stocktrade.bizruntime.com/", className = "com.bizruntime.stocktrade.GetMaxVolumeTrade")
    @ResponseWrapper(localName = "getMaxVolumeTradeResponse", targetNamespace = "http://stocktrade.bizruntime.com/", className = "com.bizruntime.stocktrade.GetMaxVolumeTradeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.bizruntime.stocktrade.StockTrdae getMaxVolumeTrade(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMinVolumeTrade", targetNamespace = "http://stocktrade.bizruntime.com/", className = "com.bizruntime.stocktrade.GetMinVolumeTrade")
    @ResponseWrapper(localName = "getMinVolumeTradeResponse", targetNamespace = "http://stocktrade.bizruntime.com/", className = "com.bizruntime.stocktrade.GetMinVolumeTradeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.bizruntime.stocktrade.StockTrdae getMinVolumeTrade(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "readStockTrades", targetNamespace = "http://stocktrade.bizruntime.com/", className = "com.bizruntime.stocktrade.ReadStockTrades")
    @ResponseWrapper(localName = "readStockTradesResponse", targetNamespace = "http://stocktrade.bizruntime.com/", className = "com.bizruntime.stocktrade.ReadStockTradesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.bizruntime.stocktrade.StockTrdae> readStockTrades() throws StockTradeInValidFormatException_Exception;
}
