
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.bizruntime.stocktrade;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-03T18:37:38.002+05:30
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "CSVStockTradeReaderService",
                      portName = "CSVStockTradeReaderPort",
                      targetNamespace = "http://stocktrade.bizruntime.com/",
                      wsdlLocation = "file:/D:/JOB/ClientSideStockTrade/csvstocktradereader.wsdl",
                      endpointInterface = "com.bizruntime.stocktrade.CSVStockTradeReader")
                      
public class CSVStockTradeReaderImpl implements CSVStockTradeReader {

    private static final Logger LOG = Logger.getLogger(CSVStockTradeReaderImpl.class.getName());

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getDailyTradingDifferential(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return getDailyTradingDifferential(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getDailyTradingDifferential");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return _return = new com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return();
            java.util.List<com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry> _returnEntry = new java.util.ArrayList<com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry>();
            com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry _returnEntryVal1 = new com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry();
            com.bizruntime.stocktrade.Date _returnEntryVal1Key = new com.bizruntime.stocktrade.Date();
            _returnEntryVal1.setKey(_returnEntryVal1Key);
            _returnEntryVal1.setValue(Double.valueOf(0.7742332394863715));
            _returnEntry.add(_returnEntryVal1);
            _return.getEntry().addAll(_returnEntry);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getMaxVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.StockTrdae getMaxVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getMaxVolumeTrade");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.StockTrdae _return = new com.bizruntime.stocktrade.StockTrdae();
            _return.setAdjClose(Double.valueOf(0.8884563662224048));
            _return.setClose(Double.valueOf(0.12284252654881211));
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-03T18:37:38.015+05:30"));
            _return.setHigh(Double.valueOf(0.7100000071260105));
            _return.setLow(Double.valueOf(0.9848450913045067));
            _return.setOpen(Double.valueOf(0.5934508034455865));
            _return.setSecurity("Security503068043");
            _return.setVolume(Double.valueOf(0.772140149788967));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getMinVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.StockTrdae getMinVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getMinVolumeTrade");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.StockTrdae _return = new com.bizruntime.stocktrade.StockTrdae();
            _return.setAdjClose(Double.valueOf(0.02747531063864539));
            _return.setClose(Double.valueOf(0.43370535452457504));
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-03T18:37:38.016+05:30"));
            _return.setHigh(Double.valueOf(0.008022849210889804));
            _return.setLow(Double.valueOf(0.19516633254405635));
            _return.setOpen(Double.valueOf(0.08504704728984103));
            _return.setSecurity("Security-616074323");
            _return.setVolume(Double.valueOf(0.8983389129733654));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#readStockTrades(*
     */
    public java.util.List<com.bizruntime.stocktrade.StockTrdae> readStockTrades() throws StockTradeInValidFormatException_Exception    { 
        LOG.info("Executing operation readStockTrades");
        try {
            java.util.List<com.bizruntime.stocktrade.StockTrdae> _return = new java.util.ArrayList<com.bizruntime.stocktrade.StockTrdae>();
            com.bizruntime.stocktrade.StockTrdae _returnVal1 = new com.bizruntime.stocktrade.StockTrdae();
            _returnVal1.setAdjClose(Double.valueOf(0.09290521491626369));
            _returnVal1.setClose(Double.valueOf(0.5773627788084713));
            _returnVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-03T18:37:38.017+05:30"));
            _returnVal1.setHigh(Double.valueOf(0.8907391262278573));
            _returnVal1.setLow(Double.valueOf(0.7047437802109835));
            _returnVal1.setOpen(Double.valueOf(0.4584012857908647));
            _returnVal1.setSecurity("Security-429344829");
            _returnVal1.setVolume(Double.valueOf(0.27301696762115424));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StockTradeInValidFormatException_Exception("StockTradeInValidFormatException...");
    }

}
