package com.bizruntime.productavailabilityservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-05T16:13:46.358+05:30
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://productavailabilityservice.bizruntime.com/", name = "productavailabilityservice")
@XmlSeeAlso({ObjectFactory.class})
public interface Productavailabilityservice {

    @WebMethod
    @RequestWrapper(localName = "getAllProductForUserForCategory", targetNamespace = "http://productavailabilityservice.bizruntime.com/", className = "com.bizruntime.productavailabilityservice.GetAllProductForUserForCategory")
    @ResponseWrapper(localName = "getAllProductForUserForCategoryResponse", targetNamespace = "http://productavailabilityservice.bizruntime.com/", className = "com.bizruntime.productavailabilityservice.GetAllProductForUserForCategoryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.bizruntime.productavailabilityservice.Product> getAllProductForUserForCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getAllProductForUser", targetNamespace = "http://productavailabilityservice.bizruntime.com/", className = "com.bizruntime.productavailabilityservice.GetAllProductForUser")
    @ResponseWrapper(localName = "getAllProductForUserResponse", targetNamespace = "http://productavailabilityservice.bizruntime.com/", className = "com.bizruntime.productavailabilityservice.GetAllProductForUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.bizruntime.productavailabilityservice.Product> getAllProductForUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
