
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.bizruntime.productavailabilityservice;

import java.util.List;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.bizruntime.UserProductMaven.Product;
import com.bizruntime.UserProductMaven.ProductAvailabilityService;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-05T16:13:46.301+05:30
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "productavailabilityservice",
                      portName = "productavailabilityserviceSOAPPort",
                      targetNamespace = "http://productavailabilityservice.bizruntime.com/",
                      wsdlLocation = "file:/D:/JOB/UserProductMaven/src/main/webapp/wsdl/productavailabilityservice.wsdl",
                      endpointInterface = "com.bizruntime.productavailabilityservice.Productavailabilityservice")
                      
public class ProductavailabilityserviceImpl implements Productavailabilityservice {

    private static final Logger LOG = Logger.getLogger(ProductavailabilityserviceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.bizruntime.productavailabilityservice.Productavailabilityservice#getAllProductForUserForCategory(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.util.List<com.bizruntime.productavailabilityservice.Product> getAllProductForUserForCategory(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getAllProductForUserForCategory");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<com.bizruntime.productavailabilityservice.Product> _return = new java.util.ArrayList<com.bizruntime.productavailabilityservice.Product>();
            com.bizruntime.productavailabilityservice.Product _returnVal1 = new com.bizruntime.productavailabilityservice.Product();
            _returnVal1.setProductId("ProductId1120380608");
            _returnVal1.setProductName("ProductName1954884265");
            _returnVal1.setProductCategory("ProductCategory-1365730618");
            _returnVal1.setPrice(0.24202774386430492);
            _returnVal1.setAvailableCity("AvailableCity325175486");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.productavailabilityservice.Productavailabilityservice#getAllProductForUser(java.lang.String  arg0 )*
     */
    public java.util.List<com.bizruntime.productavailabilityservice.Product> getAllProductForUser(java.lang.String arg0) { 
        LOG.info("Executing operation getAllProductForUser");
        System.out.println(arg0);
        try {
        	ProductAvailabilityService service = new ProductAvailabilityService();
        	List<Product> list = service.getAllProductForUser(arg0);
        	System.out.println(list);
        	
        	
            java.util.List<com.bizruntime.productavailabilityservice.Product> _return = new java.util.ArrayList<com.bizruntime.productavailabilityservice.Product>();
            com.bizruntime.productavailabilityservice.Product _returnVal1 = new com.bizruntime.productavailabilityservice.Product();
            _returnVal1.setProductId("ProductId-111872720");
            _returnVal1.setProductName("ProductName1380574381");
            _returnVal1.setProductCategory("ProductCategory-566661640");
            _returnVal1.setPrice(0.5454789422414561);
            _returnVal1.setAvailableCity("AvailableCity467158187");
            _return.add(_returnVal1);
            return _return;
        
            
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
