package org.tempuri.areaservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-03T16:43:48.831+05:30
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "AreaService", 
                  wsdlLocation = "file:/D:/JOB/AreaProj/WebContent/AreaService.wsdl",
                  targetNamespace = "http://tempuri.org/AreaService/") 
public class AreaService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/AreaService/", "AreaService");
    public final static QName AreaServiceSOAP = new QName("http://tempuri.org/AreaService/", "AreaServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/JOB/AreaProj/WebContent/AreaService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AreaService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/JOB/AreaProj/WebContent/AreaService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AreaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AreaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AreaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AreaService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AreaService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AreaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AreaService
     */
    @WebEndpoint(name = "AreaServiceSOAP")
    public AreaService getAreaServiceSOAP() {
        return super.getPort(AreaServiceSOAP, AreaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AreaService
     */
    @WebEndpoint(name = "AreaServiceSOAP")
    public AreaService getAreaServiceSOAP(WebServiceFeature... features) {
        return super.getPort(AreaServiceSOAP, AreaService.class, features);
    }

}
