
package com.bizruntime.stocktrade.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.3
 * Fri Mar 03 13:03:57 IST 2017
 * Generated source version: 2.6.3
 */

@XmlRootElement(name = "getDailyTradingDifferentialResponse", namespace = "http://stocktrade.bizruntime.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDailyTradingDifferentialResponse", namespace = "http://stocktrade.bizruntime.com/")

public class GetDailyTradingDifferentialResponse {

    @XmlElement(name = "return")
    private java.util.Map<java.sql.Date, java.lang.Double> _return;

    public java.util.Map<java.sql.Date, java.lang.Double> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.Map<java.sql.Date, java.lang.Double> new_return)  {
        this._return = new_return;
    }

}

