
package com.bizruntime.stocktrade.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.3
 * Fri Mar 03 13:03:56 IST 2017
 * Generated source version: 2.6.3
 */

@XmlRootElement(name = "getMinVolumeTradeResponse", namespace = "http://stocktrade.bizruntime.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMinVolumeTradeResponse", namespace = "http://stocktrade.bizruntime.com/")

public class GetMinVolumeTradeResponse {

    @XmlElement(name = "return")
    private com.bizruntime.stocktrade.StockTrdae _return;

    public com.bizruntime.stocktrade.StockTrdae getReturn() {
        return this._return;
    }

    public void setReturn(com.bizruntime.stocktrade.StockTrdae new_return)  {
        this._return = new_return;
    }

}

