
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.bizruntime.stocktrade;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-03T16:25:39.130+05:30
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "CSVStockTradeReaderService",
                      portName = "CSVStockTradeReaderPort",
                      targetNamespace = "http://stocktrade.bizruntime.com/",
                      wsdlLocation = "file:/D:/JOB/ClientWithMaven/src/main/resources/csvstocktradereader.wsdl",
                      endpointInterface = "com.bizruntime.stocktrade.CSVStockTradeReader")
                      
public class CSVStockTradeReaderImpl implements CSVStockTradeReader {

    private static final Logger LOG = Logger.getLogger(CSVStockTradeReaderImpl.class.getName());

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getDailyTradingDifferential(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return getDailyTradingDifferential(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getDailyTradingDifferential");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return _return = new com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return();
            java.util.List<com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry> _returnEntry = new java.util.ArrayList<com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry>();
            com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry _returnEntryVal1 = new com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry();
            com.bizruntime.stocktrade.Date _returnEntryVal1Key = new com.bizruntime.stocktrade.Date();
            _returnEntryVal1.setKey(_returnEntryVal1Key);
            _returnEntryVal1.setValue(Double.valueOf(0.7929023568115902));
            _returnEntry.add(_returnEntryVal1);
            _return.getEntry().addAll(_returnEntry);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getMaxVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.StockTrdae getMaxVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getMaxVolumeTrade");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.StockTrdae _return = new com.bizruntime.stocktrade.StockTrdae();
            _return.setAdjClose(Double.valueOf(0.24745957665680363));
            _return.setClose(Double.valueOf(0.3531847489014476));
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-03T16:25:39.144+05:30"));
            _return.setHigh(Double.valueOf(0.32419928771667805));
            _return.setLow(Double.valueOf(0.25263984261382855));
            _return.setOpen(Double.valueOf(0.8569633869615567));
            _return.setSecurity("Security303483273");
            _return.setVolume(Double.valueOf(0.3767779085838514));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getMinVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.StockTrdae getMinVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getMinVolumeTrade");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.StockTrdae _return = new com.bizruntime.stocktrade.StockTrdae();
            _return.setAdjClose(Double.valueOf(0.9654005388080075));
            _return.setClose(Double.valueOf(0.3933222859022004));
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-03T16:25:39.145+05:30"));
            _return.setHigh(Double.valueOf(0.35102114649782123));
            _return.setLow(Double.valueOf(0.17036269077756594));
            _return.setOpen(Double.valueOf(0.49952989397249525));
            _return.setSecurity("Security1021568077");
            _return.setVolume(Double.valueOf(0.3673406166545323));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#readStockTrades(*
     */
    public java.util.List<com.bizruntime.stocktrade.StockTrdae> readStockTrades() throws StockTradeInValidFormatException_Exception    { 
        LOG.info("Executing operation readStockTrades");
        try {
            java.util.List<com.bizruntime.stocktrade.StockTrdae> _return = new java.util.ArrayList<com.bizruntime.stocktrade.StockTrdae>();
            com.bizruntime.stocktrade.StockTrdae _returnVal1 = new com.bizruntime.stocktrade.StockTrdae();
            _returnVal1.setAdjClose(Double.valueOf(0.1286025641100509));
            _returnVal1.setClose(Double.valueOf(0.5808998457233145));
            _returnVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-03T16:25:39.150+05:30"));
            _returnVal1.setHigh(Double.valueOf(0.14007331316402483));
            _returnVal1.setLow(Double.valueOf(0.11454432455981356));
            _returnVal1.setOpen(Double.valueOf(0.13689378909911198));
            _returnVal1.setSecurity("Security326324063");
            _returnVal1.setVolume(Double.valueOf(0.7852312747172769));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StockTradeInValidFormatException_Exception("StockTradeInValidFormatException...");
    }

}
