
package com.bizruntime.userproduct;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-04T12:06:20.173+05:30
 * Generated source version: 2.6.3
 */

@WebFault(name = "ResourceNotFoundException", targetNamespace = "http://userproduct.bizruntime.com/")
public class ResourceNotFoundException_Exception extends Exception {
    
    private com.bizruntime.userproduct.ResourceNotFoundException resourceNotFoundException;

    public ResourceNotFoundException_Exception() {
        super();
    }
    
    public ResourceNotFoundException_Exception(String message) {
        super(message);
    }
    
    public ResourceNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceNotFoundException_Exception(String message, com.bizruntime.userproduct.ResourceNotFoundException resourceNotFoundException) {
        super(message);
        this.resourceNotFoundException = resourceNotFoundException;
    }

    public ResourceNotFoundException_Exception(String message, com.bizruntime.userproduct.ResourceNotFoundException resourceNotFoundException, Throwable cause) {
        super(message, cause);
        this.resourceNotFoundException = resourceNotFoundException;
    }

    public com.bizruntime.userproduct.ResourceNotFoundException getFaultInfo() {
        return this.resourceNotFoundException;
    }
}
