
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.bizruntime.stocktrade;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-04T09:57:06.114+05:30
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "CSVStockTradeReaderService",
                      portName = "CSVStockTradeReaderPort",
                      targetNamespace = "http://stocktrade.bizruntime.com/",
                      wsdlLocation = "file:/D:/JOB/ClientSideOP/csvstocktradereader.wsdl",
                      endpointInterface = "com.bizruntime.stocktrade.CSVStockTradeReader")
                      
public class CSVStockTradeReaderImpl implements CSVStockTradeReader {

    private static final Logger LOG = Logger.getLogger(CSVStockTradeReaderImpl.class.getName());

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getDailyTradingDifferential(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return getDailyTradingDifferential(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getDailyTradingDifferential");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return _return = new com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return();
            java.util.List<com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry> _returnEntry = new java.util.ArrayList<com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry>();
            com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry _returnEntryVal1 = new com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry();
            com.bizruntime.stocktrade.Date _returnEntryVal1Key = new com.bizruntime.stocktrade.Date();
            _returnEntryVal1.setKey(_returnEntryVal1Key);
            _returnEntryVal1.setValue(Double.valueOf(0.9027646768278067));
            _returnEntry.add(_returnEntryVal1);
            _return.getEntry().addAll(_returnEntry);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getMaxVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.StockTrdae getMaxVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getMaxVolumeTrade");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.StockTrdae _return = new com.bizruntime.stocktrade.StockTrdae();
            _return.setAdjClose(Double.valueOf(0.8846983497973486));
            _return.setClose(Double.valueOf(0.06288938825287926));
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-04T09:57:06.126+05:30"));
            _return.setHigh(Double.valueOf(0.6769620699797939));
            _return.setLow(Double.valueOf(0.8326491949824214));
            _return.setOpen(Double.valueOf(0.6229507324471945));
            _return.setSecurity("Security1989392674");
            _return.setVolume(Double.valueOf(0.035163394675542414));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getMinVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.StockTrdae getMinVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getMinVolumeTrade");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.StockTrdae _return = new com.bizruntime.stocktrade.StockTrdae();
            _return.setAdjClose(Double.valueOf(0.2606683794656036));
            _return.setClose(Double.valueOf(0.4244627961216446));
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-04T09:57:06.128+05:30"));
            _return.setHigh(Double.valueOf(0.9072165722638886));
            _return.setLow(Double.valueOf(0.007890425052382022));
            _return.setOpen(Double.valueOf(0.9387351003442894));
            _return.setSecurity("Security1515086597");
            _return.setVolume(Double.valueOf(0.5261614382921438));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#readStockTrades(*
     */
    public java.util.List<com.bizruntime.stocktrade.StockTrdae> readStockTrades() throws StockTradeInValidFormatException_Exception    { 
        LOG.info("Executing operation readStockTrades");
        try {
            java.util.List<com.bizruntime.stocktrade.StockTrdae> _return = new java.util.ArrayList<com.bizruntime.stocktrade.StockTrdae>();
            com.bizruntime.stocktrade.StockTrdae _returnVal1 = new com.bizruntime.stocktrade.StockTrdae();
            _returnVal1.setAdjClose(Double.valueOf(0.9109847634732537));
            _returnVal1.setClose(Double.valueOf(0.686052895441141));
            _returnVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-04T09:57:06.129+05:30"));
            _returnVal1.setHigh(Double.valueOf(0.014900900443448495));
            _returnVal1.setLow(Double.valueOf(0.7991676598769353));
            _returnVal1.setOpen(Double.valueOf(0.9488669613888194));
            _returnVal1.setSecurity("Security-1349180421");
            _returnVal1.setVolume(Double.valueOf(0.5063346295227004));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StockTradeInValidFormatException_Exception("StockTradeInValidFormatException...");
    }

}
