
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.bizruntime.stocktrade;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-03T15:37:56.842+05:30
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "CSVStockTradeReaderService",
                      portName = "CSVStockTradeReaderPort",
                      targetNamespace = "http://stocktrade.bizruntime.com/",
                      wsdlLocation = "file:/D:/JOB/ClientStockTrade/csvstocktradereader.wsdl",
                      endpointInterface = "com.bizruntime.stocktrade.CSVStockTradeReader")
                      
public class CSVStockTradeReaderImpl implements CSVStockTradeReader {

    private static final Logger LOG = Logger.getLogger(CSVStockTradeReaderImpl.class.getName());

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getDailyTradingDifferential(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return getDailyTradingDifferential(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getDailyTradingDifferential");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return _return = new com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return();
            java.util.List<com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry> _returnEntry = new java.util.ArrayList<com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry>();
            com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry _returnEntryVal1 = new com.bizruntime.stocktrade.GetDailyTradingDifferentialResponse.Return.Entry();
            com.bizruntime.stocktrade.Date _returnEntryVal1Key = new com.bizruntime.stocktrade.Date();
            _returnEntryVal1.setKey(_returnEntryVal1Key);
            _returnEntryVal1.setValue(Double.valueOf(0.09412060839931158));
            _returnEntry.add(_returnEntryVal1);
            _return.getEntry().addAll(_returnEntry);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getMaxVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.StockTrdae getMaxVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getMaxVolumeTrade");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.StockTrdae _return = new com.bizruntime.stocktrade.StockTrdae();
            _return.setAdj_Close(Double.valueOf(0.939436832855826));
            _return.setClose(Double.valueOf(0.719449838222655));
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-03T15:37:56.860+05:30"));
            _return.setHigh(Double.valueOf(0.29711161822630117));
            _return.setLow(Double.valueOf(0.6280019674505868));
            _return.setOpen(Double.valueOf(0.792524249751863));
            _return.setSecurity("Security-752184526");
            _return.setVolume(Double.valueOf(0.03864911134381688));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#getMinVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae>  arg0 )*
     */
    public com.bizruntime.stocktrade.StockTrdae getMinVolumeTrade(java.util.List<com.bizruntime.stocktrade.StockTrdae> arg0) { 
        LOG.info("Executing operation getMinVolumeTrade");
        System.out.println(arg0);
        try {
            com.bizruntime.stocktrade.StockTrdae _return = new com.bizruntime.stocktrade.StockTrdae();
            _return.setAdj_Close(Double.valueOf(0.7433013558710272));
            _return.setClose(Double.valueOf(0.8022817448470924));
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-03T15:37:56.862+05:30"));
            _return.setHigh(Double.valueOf(0.2223885717339975));
            _return.setLow(Double.valueOf(0.5692956156240757));
            _return.setOpen(Double.valueOf(0.8248991172957766));
            _return.setSecurity("Security-381755257");
            _return.setVolume(Double.valueOf(0.891603378269566));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bizruntime.stocktrade.CSVStockTradeReader#readStockTrades(*
     */
    public java.util.List<com.bizruntime.stocktrade.StockTrdae> readStockTrades() throws StockTradeInValidFormatException_Exception    { 
        LOG.info("Executing operation readStockTrades");
        try {
            java.util.List<com.bizruntime.stocktrade.StockTrdae> _return = new java.util.ArrayList<com.bizruntime.stocktrade.StockTrdae>();
            com.bizruntime.stocktrade.StockTrdae _returnVal1 = new com.bizruntime.stocktrade.StockTrdae();
            _returnVal1.setAdj_Close(Double.valueOf(0.15731435041424857));
            _returnVal1.setClose(Double.valueOf(0.9313361758734293));
            _returnVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-03T15:37:56.863+05:30"));
            _returnVal1.setHigh(Double.valueOf(0.5815986655936972));
            _returnVal1.setLow(Double.valueOf(0.9924339356295275));
            _returnVal1.setOpen(Double.valueOf(0.9155611459113295));
            _returnVal1.setSecurity("Security-1618198816");
            _returnVal1.setVolume(Double.valueOf(0.3123694175083902));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StockTradeInValidFormatException_Exception("StockTradeInValidFormatException...");
    }

}
