
package com.bizruntime.stocktrade;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2017-03-03T15:37:56.826+05:30
 * Generated source version: 2.6.3
 */

@WebFault(name = "StockTradeInValidFormatException", targetNamespace = "http://stocktrade.bizruntime.com/")
public class StockTradeInValidFormatException_Exception extends Exception {
    
    private com.bizruntime.stocktrade.StockTradeInValidFormatException stockTradeInValidFormatException;

    public StockTradeInValidFormatException_Exception() {
        super();
    }
    
    public StockTradeInValidFormatException_Exception(String message) {
        super(message);
    }
    
    public StockTradeInValidFormatException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public StockTradeInValidFormatException_Exception(String message, com.bizruntime.stocktrade.StockTradeInValidFormatException stockTradeInValidFormatException) {
        super(message);
        this.stockTradeInValidFormatException = stockTradeInValidFormatException;
    }

    public StockTradeInValidFormatException_Exception(String message, com.bizruntime.stocktrade.StockTradeInValidFormatException stockTradeInValidFormatException, Throwable cause) {
        super(message, cause);
        this.stockTradeInValidFormatException = stockTradeInValidFormatException;
    }

    public com.bizruntime.stocktrade.StockTradeInValidFormatException getFaultInfo() {
        return this.stockTradeInValidFormatException;
    }
}
